name: dscim-testing
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.8
  - xarray==2024.3.0
  - pandas==2.2.3
  - numpy==1.26.4
  - matplotlib==3.10.0
  - dask[array, distributed]==2025.1.0
  - requests==2.32.3
  - statsmodels==0.14.4
  - pytest==8.3.4
  - pytest-cov==6.0.0
  - zarr==2.18.4
  - ruff==0.8.6
  - netcdf4==1.7.2
  - h5netcdf==1.5.0
  - pyarrow==19.0.0
  - pip==25.0.1
  - geopandas
  - cartopy
  - pip:
      - dask_jobqueue==0.8.2
      - p_tqdm==1.4.2
      - impactlab-tools==0.6.0
      - inquirer==2.10.0
      - pyyaml==6.0.1
      - dscim
